FROM node:20-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./package-lock.json ./package-lock.json
COPY ./package.json ./package.json 
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend


RUN npm install


ARG DATABASE_URL
RUN echo $DATABSE_URL
ENV DATABASE_URL=$DATABASE_URL
RUN npm run db:generate


EXPOSE 3002

CMD ["npm" , "run" , "start:http-backend"]