FROM node:20-alpine

WORKDIR /app

COPY ./packages ./packclages
COPY ./package-lock.json ./package-loc.json
COPY ./package.json ./package.json 
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN npm install
RUN npm run db:generate


EXPOSE 3002

CMD ["npm" , "run" , "start:http-backend"]