FROM node:20-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./package-lock.json ./package-lock.json
COPY ./package.json ./package.json 
COPY ./turbo.json ./turbo.json

COPY ./apps/excalidraw_frontend ./apps/excalidraw_frontend

RUN npm install
# to ensure prisma client exists

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
RUN npm run db:generate  
RUN npx turbo run build --filter=excalidraw_frontend



EXPOSE 3000

CMD ["npm" , "run" , "start:web"]